/**
  https://school.programmers.co.kr/learn/courses/30/lessons/59042
  없어진 기록 찾기
 */
-- RIGHT OUTER JOIN
SELECT OUTS.ANIMAL_ID, OUTS.NAME FROM ANIMAL_INS AS INS RIGHT OUTER JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID WHERE INS.DATETIME IS NULL
-- LEFT OUTER JOIN
SELECT OUTS.ANIMAL_ID, OUTS.NAME FROM ANIMAL_OUTS AS OUTS LEFT OUTER JOIN ANIMAL_INS AS INS ON INS.ANIMAL_ID=OUTS.ANIMAL_ID WHERE INS.DATETIME IS NULL

